/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssociationValueEntry(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord>?,
    parentPath: InverseForeignKey<out Record, com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord>?,
    aliased: Table<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord>(
    alias,
    com.michal.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.association_value_entry</code>
         */
        val ASSOCIATION_VALUE_ENTRY: AssociationValueEntry = AssociationValueEntry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord> = com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord::class.java

    /**
     * The column <code>public.association_value_entry.id</code>.
     */
    val ID: TableField<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.association_value_entry.association_key</code>.
     */
    val ASSOCIATION_KEY: TableField<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord, String?> = createField(DSL.name("association_key"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.association_value_entry.association_value</code>.
     */
    val ASSOCIATION_VALUE: TableField<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord, String?> = createField(DSL.name("association_value"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.association_value_entry.saga_id</code>.
     */
    val SAGA_ID: TableField<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord, String?> = createField(DSL.name("saga_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.association_value_entry.saga_type</code>.
     */
    val SAGA_TYPE: TableField<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord, String?> = createField(DSL.name("saga_type"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.association_value_entry</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.association_value_entry</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.association_value_entry</code> table reference
     */
    constructor(): this(DSL.name("association_value_entry"), null)
    override fun getSchema(): Schema? = if (aliased()) null else com.michal.jooq.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord> = com.michal.jooq.`public`.keys.ASSOCIATION_VALUE_ENTRY_PKEY
    override fun `as`(alias: String): AssociationValueEntry = AssociationValueEntry(DSL.name(alias), this)
    override fun `as`(alias: Name): AssociationValueEntry = AssociationValueEntry(alias, this)
    override fun `as`(alias: Table<*>): AssociationValueEntry = AssociationValueEntry(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AssociationValueEntry = AssociationValueEntry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AssociationValueEntry = AssociationValueEntry(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AssociationValueEntry = AssociationValueEntry(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AssociationValueEntry = AssociationValueEntry(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AssociationValueEntry = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AssociationValueEntry = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AssociationValueEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AssociationValueEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AssociationValueEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AssociationValueEntry = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AssociationValueEntry = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AssociationValueEntry = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AssociationValueEntry = where(DSL.notExists(select))
}
