/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables


import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DeadLetterEntry(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>?,
    parentPath: InverseForeignKey<out Record, com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>?,
    aliased: Table<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>(
    alias,
    com.michal.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.dead_letter_entry</code>
         */
        val DEAD_LETTER_ENTRY: DeadLetterEntry = DeadLetterEntry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord> = com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord::class.java

    /**
     * The column <code>public.dead_letter_entry.enqueued_at</code>.
     */
    val ENQUEUED_AT: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, OffsetDateTime?> = createField(DSL.name("enqueued_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.last_touched</code>.
     */
    val LAST_TOUCHED: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, OffsetDateTime?> = createField(DSL.name("last_touched"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.dead_letter_entry.processing_started</code>.
     */
    val PROCESSING_STARTED: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, OffsetDateTime?> = createField(DSL.name("processing_started"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.dead_letter_entry.sequence_index</code>.
     */
    val SEQUENCE_INDEX: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, Long?> = createField(DSL.name("sequence_index"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.sequence_number</code>.
     */
    val SEQUENCE_NUMBER: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, Long?> = createField(DSL.name("sequence_number"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.dead_letter_entry.cause_message</code>.
     */
    val CAUSE_MESSAGE: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("cause_message"), SQLDataType.VARCHAR(1023), this, "")

    /**
     * The column <code>public.dead_letter_entry.aggregate_identifier</code>.
     */
    val AGGREGATE_IDENTIFIER: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("aggregate_identifier"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.dead_letter_entry.cause_type</code>.
     */
    val CAUSE_TYPE: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("cause_type"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.dead_letter_entry.dead_letter_id</code>.
     */
    val DEAD_LETTER_ID: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("dead_letter_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.event_identifier</code>.
     */
    val EVENT_IDENTIFIER: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("event_identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.message_type</code>.
     */
    val MESSAGE_TYPE: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("message_type"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.payload_revision</code>.
     */
    val PAYLOAD_REVISION: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("payload_revision"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.dead_letter_entry.payload_type</code>.
     */
    val PAYLOAD_TYPE: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("payload_type"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.processing_group</code>.
     */
    val PROCESSING_GROUP: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("processing_group"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.sequence_identifier</code>.
     */
    val SEQUENCE_IDENTIFIER: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("sequence_identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.time_stamp</code>.
     */
    val TIME_STAMP: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("time_stamp"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.token_type</code>.
     */
    val TOKEN_TYPE: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("token_type"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.dead_letter_entry.type</code>.
     */
    val TYPE: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.dead_letter_entry.diagnostics</code>.
     */
    val DIAGNOSTICS: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, Long?> = createField(DSL.name("diagnostics"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.dead_letter_entry.meta_data</code>.
     */
    val META_DATA: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, Long?> = createField(DSL.name("meta_data"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.dead_letter_entry.payload</code>.
     */
    val PAYLOAD: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, Long?> = createField(DSL.name("payload"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.dead_letter_entry.token</code>.
     */
    val TOKEN: TableField<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord, Long?> = createField(DSL.name("token"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.dead_letter_entry</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.dead_letter_entry</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.dead_letter_entry</code> table reference
     */
    constructor(): this(DSL.name("dead_letter_entry"), null)
    override fun getSchema(): Schema? = if (aliased()) null else com.michal.jooq.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord> = com.michal.jooq.`public`.keys.DEAD_LETTER_ENTRY_PKEY
    override fun getUniqueKeys(): List<UniqueKey<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord>> = listOf(com.michal.jooq.`public`.keys.DEAD_LETTER_ENTRY_PROCESSING_GROUP_SEQUENCE_IDENTIFIER_SEQU_KEY)
    override fun `as`(alias: String): DeadLetterEntry = DeadLetterEntry(DSL.name(alias), this)
    override fun `as`(alias: Name): DeadLetterEntry = DeadLetterEntry(alias, this)
    override fun `as`(alias: Table<*>): DeadLetterEntry = DeadLetterEntry(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DeadLetterEntry = DeadLetterEntry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DeadLetterEntry = DeadLetterEntry(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DeadLetterEntry = DeadLetterEntry(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): DeadLetterEntry = DeadLetterEntry(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DeadLetterEntry = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): DeadLetterEntry = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): DeadLetterEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DeadLetterEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DeadLetterEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DeadLetterEntry = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DeadLetterEntry = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): DeadLetterEntry = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): DeadLetterEntry = where(DSL.notExists(select))
}
