/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DomainEventEntry(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>?,
    parentPath: InverseForeignKey<out Record, com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>?,
    aliased: Table<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>(
    alias,
    com.michal.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.domain_event_entry</code>
         */
        val DOMAIN_EVENT_ENTRY: DomainEventEntry = DomainEventEntry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord> = com.michal.jooq.`public`.tables.records.DomainEventEntryRecord::class.java

    /**
     * The column <code>public.domain_event_entry.global_index</code>.
     */
    val GLOBAL_INDEX: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, Long?> = createField(DSL.name("global_index"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.domain_event_entry.sequence_number</code>.
     */
    val SEQUENCE_NUMBER: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, Long?> = createField(DSL.name("sequence_number"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.domain_event_entry.aggregate_identifier</code>.
     */
    val AGGREGATE_IDENTIFIER: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, String?> = createField(DSL.name("aggregate_identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.domain_event_entry.event_identifier</code>.
     */
    val EVENT_IDENTIFIER: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, String?> = createField(DSL.name("event_identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.domain_event_entry.payload_revision</code>.
     */
    val PAYLOAD_REVISION: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, String?> = createField(DSL.name("payload_revision"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.domain_event_entry.payload_type</code>.
     */
    val PAYLOAD_TYPE: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, String?> = createField(DSL.name("payload_type"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.domain_event_entry.time_stamp</code>.
     */
    val TIME_STAMP: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, String?> = createField(DSL.name("time_stamp"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.domain_event_entry.type</code>.
     */
    val TYPE: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.domain_event_entry.meta_data</code>.
     */
    val META_DATA: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, Long?> = createField(DSL.name("meta_data"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.domain_event_entry.payload</code>.
     */
    val PAYLOAD: TableField<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord, Long?> = createField(DSL.name("payload"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.domain_event_entry</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.domain_event_entry</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.domain_event_entry</code> table reference
     */
    constructor(): this(DSL.name("domain_event_entry"), null)
    override fun getSchema(): Schema? = if (aliased()) null else com.michal.jooq.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord> = com.michal.jooq.`public`.keys.DOMAIN_EVENT_ENTRY_PKEY
    override fun getUniqueKeys(): List<UniqueKey<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord>> = listOf(com.michal.jooq.`public`.keys.DOMAIN_EVENT_ENTRY_AGGREGATE_IDENTIFIER_SEQUENCE_NUMBER_KEY, com.michal.jooq.`public`.keys.DOMAIN_EVENT_ENTRY_EVENT_IDENTIFIER_KEY)
    override fun `as`(alias: String): DomainEventEntry = DomainEventEntry(DSL.name(alias), this)
    override fun `as`(alias: Name): DomainEventEntry = DomainEventEntry(alias, this)
    override fun `as`(alias: Table<*>): DomainEventEntry = DomainEventEntry(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DomainEventEntry = DomainEventEntry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DomainEventEntry = DomainEventEntry(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DomainEventEntry = DomainEventEntry(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): DomainEventEntry = DomainEventEntry(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DomainEventEntry = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): DomainEventEntry = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): DomainEventEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DomainEventEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DomainEventEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DomainEventEntry = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DomainEventEntry = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): DomainEventEntry = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): DomainEventEntry = where(DSL.notExists(select))
}
