/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables


import java.time.LocalDate
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class EventStore(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, com.michal.jooq.`public`.tables.records.EventStoreRecord>?,
    parentPath: InverseForeignKey<out Record, com.michal.jooq.`public`.tables.records.EventStoreRecord>?,
    aliased: Table<com.michal.jooq.`public`.tables.records.EventStoreRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<com.michal.jooq.`public`.tables.records.EventStoreRecord>(
    alias,
    com.michal.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.event_store</code>
         */
        val EVENT_STORE: EventStore = EventStore()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.michal.jooq.`public`.tables.records.EventStoreRecord> = com.michal.jooq.`public`.tables.records.EventStoreRecord::class.java

    /**
     * The column <code>public.event_store.id</code>.
     */
    val ID: TableField<com.michal.jooq.`public`.tables.records.EventStoreRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.event_store.stream_id</code>.
     */
    val STREAM_ID: TableField<com.michal.jooq.`public`.tables.records.EventStoreRecord, String?> = createField(DSL.name("stream_id"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.event_store.payload</code>.
     */
    val PAYLOAD: TableField<com.michal.jooq.`public`.tables.records.EventStoreRecord, JSONB?> = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column <code>public.event_store.metadata</code>.
     */
    val METADATA: TableField<com.michal.jooq.`public`.tables.records.EventStoreRecord, JSONB?> = createField(DSL.name("metadata"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column <code>public.event_store.version</code>.
     */
    val VERSION: TableField<com.michal.jooq.`public`.tables.records.EventStoreRecord, Int?> = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.event_store.created</code>.
     */
    val CREATED: TableField<com.michal.jooq.`public`.tables.records.EventStoreRecord, LocalDate?> = createField(DSL.name("created"), SQLDataType.LOCALDATE.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.EventStoreRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.EventStoreRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.EventStoreRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.event_store</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.event_store</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.event_store</code> table reference
     */
    constructor(): this(DSL.name("event_store"), null)
    override fun getSchema(): Schema? = if (aliased()) null else com.michal.jooq.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<com.michal.jooq.`public`.tables.records.EventStoreRecord> = com.michal.jooq.`public`.keys.EVENT_STORE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<com.michal.jooq.`public`.tables.records.EventStoreRecord>> = listOf(com.michal.jooq.`public`.keys.UNIQUE_STREAM_VERSION)
    override fun `as`(alias: String): EventStore = EventStore(DSL.name(alias), this)
    override fun `as`(alias: Name): EventStore = EventStore(alias, this)
    override fun `as`(alias: Table<*>): EventStore = EventStore(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): EventStore = EventStore(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): EventStore = EventStore(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): EventStore = EventStore(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): EventStore = EventStore(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): EventStore = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): EventStore = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): EventStore = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): EventStore = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): EventStore = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): EventStore = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): EventStore = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): EventStore = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): EventStore = where(DSL.notExists(select))
}
