/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables


import java.util.UUID

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class MerchantProjection(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, com.michal.jooq.`public`.tables.records.MerchantProjectionRecord>?,
    parentPath: InverseForeignKey<out Record, com.michal.jooq.`public`.tables.records.MerchantProjectionRecord>?,
    aliased: Table<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord>(
    alias,
    com.michal.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.merchant_projection</code>
         */
        val MERCHANT_PROJECTION: MerchantProjection = MerchantProjection()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord> = com.michal.jooq.`public`.tables.records.MerchantProjectionRecord::class.java

    /**
     * The column <code>public.merchant_projection.merchant_id</code>.
     */
    val MERCHANT_ID: TableField<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord, UUID?> = createField(DSL.name("merchant_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.merchant_projection.data</code>.
     */
    val DATA: TableField<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord, JSONB?> = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column
     * <code>public.merchant_projection.latest_sequence_number</code>.
     */
    val LATEST_SEQUENCE_NUMBER: TableField<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord, Long?> = createField(DSL.name("latest_sequence_number"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.merchant_projection</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.merchant_projection</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.merchant_projection</code> table reference
     */
    constructor(): this(DSL.name("merchant_projection"), null)
    override fun getSchema(): Schema? = if (aliased()) null else com.michal.jooq.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord> = com.michal.jooq.`public`.keys.MERCHANT_PROJECTION_PKEY
    override fun `as`(alias: String): MerchantProjection = MerchantProjection(DSL.name(alias), this)
    override fun `as`(alias: Name): MerchantProjection = MerchantProjection(alias, this)
    override fun `as`(alias: Table<*>): MerchantProjection = MerchantProjection(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): MerchantProjection = MerchantProjection(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): MerchantProjection = MerchantProjection(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): MerchantProjection = MerchantProjection(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): MerchantProjection = MerchantProjection(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): MerchantProjection = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): MerchantProjection = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): MerchantProjection = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): MerchantProjection = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): MerchantProjection = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): MerchantProjection = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): MerchantProjection = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): MerchantProjection = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): MerchantProjection = where(DSL.notExists(select))
}
