/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class SagaEntry(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, com.michal.jooq.`public`.tables.records.SagaEntryRecord>?,
    parentPath: InverseForeignKey<out Record, com.michal.jooq.`public`.tables.records.SagaEntryRecord>?,
    aliased: Table<com.michal.jooq.`public`.tables.records.SagaEntryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<com.michal.jooq.`public`.tables.records.SagaEntryRecord>(
    alias,
    com.michal.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.saga_entry</code>
         */
        val SAGA_ENTRY: SagaEntry = SagaEntry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.michal.jooq.`public`.tables.records.SagaEntryRecord> = com.michal.jooq.`public`.tables.records.SagaEntryRecord::class.java

    /**
     * The column <code>public.saga_entry.revision</code>.
     */
    val REVISION: TableField<com.michal.jooq.`public`.tables.records.SagaEntryRecord, String?> = createField(DSL.name("revision"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.saga_entry.saga_id</code>.
     */
    val SAGA_ID: TableField<com.michal.jooq.`public`.tables.records.SagaEntryRecord, String?> = createField(DSL.name("saga_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.saga_entry.saga_type</code>.
     */
    val SAGA_TYPE: TableField<com.michal.jooq.`public`.tables.records.SagaEntryRecord, String?> = createField(DSL.name("saga_type"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.saga_entry.serialized_saga</code>.
     */
    val SERIALIZED_SAGA: TableField<com.michal.jooq.`public`.tables.records.SagaEntryRecord, Long?> = createField(DSL.name("serialized_saga"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.SagaEntryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.SagaEntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.SagaEntryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.saga_entry</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.saga_entry</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.saga_entry</code> table reference
     */
    constructor(): this(DSL.name("saga_entry"), null)
    override fun getSchema(): Schema? = if (aliased()) null else com.michal.jooq.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<com.michal.jooq.`public`.tables.records.SagaEntryRecord> = com.michal.jooq.`public`.keys.SAGA_ENTRY_PKEY
    override fun `as`(alias: String): SagaEntry = SagaEntry(DSL.name(alias), this)
    override fun `as`(alias: Name): SagaEntry = SagaEntry(alias, this)
    override fun `as`(alias: Table<*>): SagaEntry = SagaEntry(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SagaEntry = SagaEntry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SagaEntry = SagaEntry(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SagaEntry = SagaEntry(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): SagaEntry = SagaEntry(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): SagaEntry = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): SagaEntry = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): SagaEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): SagaEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): SagaEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): SagaEntry = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): SagaEntry = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): SagaEntry = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): SagaEntry = where(DSL.notExists(select))
}
