/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class TokenEntry(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, com.michal.jooq.`public`.tables.records.TokenEntryRecord>?,
    parentPath: InverseForeignKey<out Record, com.michal.jooq.`public`.tables.records.TokenEntryRecord>?,
    aliased: Table<com.michal.jooq.`public`.tables.records.TokenEntryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<com.michal.jooq.`public`.tables.records.TokenEntryRecord>(
    alias,
    com.michal.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.token_entry</code>
         */
        val TOKEN_ENTRY: TokenEntry = TokenEntry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.michal.jooq.`public`.tables.records.TokenEntryRecord> = com.michal.jooq.`public`.tables.records.TokenEntryRecord::class.java

    /**
     * The column <code>public.token_entry.segment</code>.
     */
    val SEGMENT: TableField<com.michal.jooq.`public`.tables.records.TokenEntryRecord, Int?> = createField(DSL.name("segment"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.token_entry.owner</code>.
     */
    val OWNER: TableField<com.michal.jooq.`public`.tables.records.TokenEntryRecord, String?> = createField(DSL.name("owner"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.token_entry.processor_name</code>.
     */
    val PROCESSOR_NAME: TableField<com.michal.jooq.`public`.tables.records.TokenEntryRecord, String?> = createField(DSL.name("processor_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.token_entry.timestamp</code>.
     */
    val TIMESTAMP: TableField<com.michal.jooq.`public`.tables.records.TokenEntryRecord, String?> = createField(DSL.name("timestamp"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.token_entry.token_type</code>.
     */
    val TOKEN_TYPE: TableField<com.michal.jooq.`public`.tables.records.TokenEntryRecord, String?> = createField(DSL.name("token_type"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.token_entry.token</code>.
     */
    val TOKEN: TableField<com.michal.jooq.`public`.tables.records.TokenEntryRecord, Long?> = createField(DSL.name("token"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.TokenEntryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.TokenEntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<com.michal.jooq.`public`.tables.records.TokenEntryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.token_entry</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.token_entry</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.token_entry</code> table reference
     */
    constructor(): this(DSL.name("token_entry"), null)
    override fun getSchema(): Schema? = if (aliased()) null else com.michal.jooq.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<com.michal.jooq.`public`.tables.records.TokenEntryRecord> = com.michal.jooq.`public`.keys.TOKEN_ENTRY_PKEY
    override fun `as`(alias: String): TokenEntry = TokenEntry(DSL.name(alias), this)
    override fun `as`(alias: Name): TokenEntry = TokenEntry(alias, this)
    override fun `as`(alias: Table<*>): TokenEntry = TokenEntry(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TokenEntry = TokenEntry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TokenEntry = TokenEntry(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TokenEntry = TokenEntry(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TokenEntry = TokenEntry(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TokenEntry = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TokenEntry = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TokenEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TokenEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TokenEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TokenEntry = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TokenEntry = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TokenEntry = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TokenEntry = where(DSL.notExists(select))
}
