services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: event-sourcing-playground
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432'
