@merchant_id = a7272acd-8007-41dd-8ef0-01f69f29eaa5
@processing_group = merchants

### Find all merchants
GET http://localhost:8080/merchants

### Onboard merchant
POST http://localhost:8080/merchants
Content-Type: application/json

{
  "merchantId": "{{merchant_id}}",
  "platformId": "e6ceecdb-5ad0-454d-a428-f9f0f873f69b",
  "merchantExternalId": "026c516959354797bd1a7bdc03e2e8c4",
  "countryCode": "USA",
  "postCode": "08030",
  "city": "Washington DC",
  "addressLine1": "Trumpstreet",
  "addressLine2": null,
  "currencyCode": "USD",
  "kitchenTypes": [
    "Korean",
    "Asian"
  ]
}

### Find merchant by ID
GET http://localhost:8080/merchants/{{merchant_id}}

### Submit PII data V1
POST http://localhost:8080/merchants/{{merchant_id}}/pii-data
Content-Type: application/json

{
  "name": "Paulo Merido",
  "email": "paulo.merido@hello.com",
  "vatNumber": "123456789",
  "registrationNumber": "987654321",
  "countryCode": "USA",
  "postCode": "08030",
  "city": "Washington DC",
  "addressLine1": "Trumpstreet 4",
  "addressLine2": "Block 1"
}

### Submit PII data V2
POST http://localhost:8080/merchants/{{merchant_id}}/pii-data
Content-Type: application/json

{
  "name": "Jennifer Shinde",
  "email": "jennifer.shinde@hello.com",
  "vatNumber": "45678901",
  "registrationNumber": "76540987",
  "countryCode": "USA",
  "postCode": "08031",
  "city": "Chicago",
  "addressLine1": "Cali 123",
  "addressLine2": null
}

### Find merchant by ID
GET http://localhost:8080/merchants/{{merchant_id}}

### Find specific version of merchant's PII data
GET http://localhost:8080/merchants/{{merchant_id}}/pii-data/1

### Find specific version of merchant's PII data
GET http://localhost:8080/merchants/{{merchant_id}}/pii-data/2

### Reconcile PII data V1 - V2
POST http://localhost:8080/merchants/{{merchant_id}}/pii-data/reconcile
Content-Type: application/json

{
  "olderVersion": 1,
  "newerVersion": 2,
  "reconciledName": "Jennifer Shinde",
  "reconciledVatNumber": "45678901",
  "reconciledRegistrationNumber": "76540987",
  "reconciledCountryCode": "USA",
  "reconciledPostCode": "08031",
  "reconciledCity": "Chicago",
  "reconciledAddressLine1": "Cali 123",
  "reconciledAddressLine2": null
}

### Submit PII data V3
POST http://localhost:8080/merchants/{{merchant_id}}/pii-data
Content-Type: application/json

{
  "name": "Mona Chauhan",
  "email": "mona.chauhan@hello.com",
  "vatNumber": "98754567",
  "registrationNumber": "345678987",
  "countryCode": "USA",
  "postCode": "08032",
  "city": "San Francisco",
  "addressLine1": "Sesame street 33",
  "addressLine2": "2nd floor"
}

### Find merchant by ID
GET http://localhost:8080/merchants/{{merchant_id}}

### Find specific version of merchant's PII data
GET http://localhost:8080/merchants/{{merchant_id}}/pii-data/2

### Find specific version of merchant's PII data
GET http://localhost:8080/merchants/{{merchant_id}}/pii-data/3

### Reconcile PII data V2 - V3
POST http://localhost:8080/merchants/{{merchant_id}}/pii-data/reconcile
Content-Type: application/json

{
  "olderVersion": 2,
  "newerVersion": 3,
  "reconciledName": "Jennifer Shinde",
  "reconciledVatNumber": "45678901",
  "reconciledRegistrationNumber": "76540987",
  "reconciledCountryCode": "USA",
  "reconciledPostCode": "08032",
  "reconciledCity": "San Francisco",
  "reconciledAddressLine1": "Sesame street 33",
  "reconciledAddressLine2": "2nd floor"
}

### Find merchant by ID
GET http://localhost:8080/merchants/{{merchant_id}}

### Reprocess DLQ
POST http://localhost:8080/internal/events/dead-letter/{{processing_group}}/{{merchant_id}}/retry

### Replay events
POST http://localhost:8080/internal/events/{{processing_group}}/replay

### Get all events
GET http://localhost:8080/internal/events/merchant/{{merchant_id}}
