POST http://localhost:8080/merchants
Content-Type: application/json

{
  "merchantId": "3ec978bf-cf83-42cb-8117-5b255b71bac7",
  "countryCode": "DEU",
  "currencyCode": "EUR"
}

### Reprocess DLQ
POST http://localhost:8080/internal/events/dead-letter/merchants/retry

###

GET http://localhost:8080/internal/events/ed7582b7-e4f0-43fe-87ae-8478a0c5ece0
