POST http://localhost:8080/merchants
Content-Type: application/json

{
  "merchantId": "a9c5fdcc-e5bc-4eac-b30d-27112235364a",
  "countryCode": "DEU",
  "currencyCode": "EUR"
}

###

GET http://localhost:8080/internal/events/a9c5fdcc-e5bc-4eac-b30d-27112235364a
