@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_STREAM_ID: Index = Internal.createIndex(DSL.name("idx_stream_id"), com.michal.jooq.`public`.tables.EventStore.EVENT_STORE, arrayOf(com.michal.jooq.`public`.tables.EventStore.EVENT_STORE.STREAM_ID), false)
