@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.sequences


import org.jooq.Sequence
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>public.domain_event_entry_seq</code>
 */
val DOMAIN_EVENT_ENTRY_SEQ: Sequence<Long> = Internal.createSequence("domain_event_entry_seq", com.michal.jooq.`public`.Public.PUBLIC, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, 50, null, null, false, null)
