@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val ASSOCIATION_VALUE_ENTRY_PKEY: UniqueKey<com.michal.jooq.`public`.tables.records.AssociationValueEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.AssociationValueEntry.ASSOCIATION_VALUE_ENTRY, DSL.name("association_value_entry_pkey"), arrayOf(com.michal.jooq.`public`.tables.AssociationValueEntry.ASSOCIATION_VALUE_ENTRY.ID), true)
val DEAD_LETTER_ENTRY_PKEY: UniqueKey<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY, DSL.name("dead_letter_entry_pkey"), arrayOf(com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY.DEAD_LETTER_ID), true)
val DEAD_LETTER_ENTRY_PROCESSING_GROUP_SEQUENCE_IDENTIFIER_SEQU_KEY: UniqueKey<com.michal.jooq.`public`.tables.records.DeadLetterEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY, DSL.name("dead_letter_entry_processing_group_sequence_identifier_sequ_key"), arrayOf(com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY.PROCESSING_GROUP, com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY.SEQUENCE_IDENTIFIER, com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY.SEQUENCE_INDEX), true)
val DOMAIN_EVENT_ENTRY_AGGREGATE_IDENTIFIER_SEQUENCE_NUMBER_KEY: UniqueKey<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY, DSL.name("domain_event_entry_aggregate_identifier_sequence_number_key"), arrayOf(com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY.AGGREGATE_IDENTIFIER, com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY.SEQUENCE_NUMBER), true)
val DOMAIN_EVENT_ENTRY_EVENT_IDENTIFIER_KEY: UniqueKey<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY, DSL.name("domain_event_entry_event_identifier_key"), arrayOf(com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY.EVENT_IDENTIFIER), true)
val DOMAIN_EVENT_ENTRY_PKEY: UniqueKey<com.michal.jooq.`public`.tables.records.DomainEventEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY, DSL.name("domain_event_entry_pkey"), arrayOf(com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY.GLOBAL_INDEX), true)
val MERCHANT_PROJECTION_PKEY: UniqueKey<com.michal.jooq.`public`.tables.records.MerchantProjectionRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.MerchantProjection.MERCHANT_PROJECTION, DSL.name("merchant_projection_pkey"), arrayOf(com.michal.jooq.`public`.tables.MerchantProjection.MERCHANT_PROJECTION.MERCHANT_ID), true)
val SAGA_ENTRY_PKEY: UniqueKey<com.michal.jooq.`public`.tables.records.SagaEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.SagaEntry.SAGA_ENTRY, DSL.name("saga_entry_pkey"), arrayOf(com.michal.jooq.`public`.tables.SagaEntry.SAGA_ENTRY.SAGA_ID), true)
val SNAPSHOT_EVENT_ENTRY_EVENT_IDENTIFIER_KEY: UniqueKey<com.michal.jooq.`public`.tables.records.SnapshotEventEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY, DSL.name("snapshot_event_entry_event_identifier_key"), arrayOf(com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.EVENT_IDENTIFIER), true)
val SNAPSHOT_EVENT_ENTRY_PKEY: UniqueKey<com.michal.jooq.`public`.tables.records.SnapshotEventEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY, DSL.name("snapshot_event_entry_pkey"), arrayOf(com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.SEQUENCE_NUMBER, com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.AGGREGATE_IDENTIFIER, com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.TYPE), true)
val TOKEN_ENTRY_PKEY: UniqueKey<com.michal.jooq.`public`.tables.records.TokenEntryRecord> = Internal.createUniqueKey(com.michal.jooq.`public`.tables.TokenEntry.TOKEN_ENTRY, DSL.name("token_entry_pkey"), arrayOf(com.michal.jooq.`public`.tables.TokenEntry.TOKEN_ENTRY.SEGMENT, com.michal.jooq.`public`.tables.TokenEntry.TOKEN_ENTRY.PROCESSOR_NAME), true)
