/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssociationValueEntryRecord() : UpdatableRecordImpl<AssociationValueEntryRecord>(com.michal.jooq.`public`.tables.AssociationValueEntry.ASSOCIATION_VALUE_ENTRY) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var associationKey: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var associationValue: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var sagaId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var sagaType: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised AssociationValueEntryRecord
     */
    constructor(id: Long? = null, associationKey: String? = null, associationValue: String? = null, sagaId: String? = null, sagaType: String? = null): this() {
        this.id = id
        this.associationKey = associationKey
        this.associationValue = associationValue
        this.sagaId = sagaId
        this.sagaType = sagaType
        resetTouchedOnNotNull()
    }
}
