/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.records


import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DeadLetterEntryRecord() : UpdatableRecordImpl<DeadLetterEntryRecord>(com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY) {

    open var enqueuedAt: OffsetDateTime?
        set(value): Unit = set(0, value)
        get(): OffsetDateTime? = get(0) as OffsetDateTime?

    open var lastTouched: OffsetDateTime?
        set(value): Unit = set(1, value)
        get(): OffsetDateTime? = get(1) as OffsetDateTime?

    open var processingStarted: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    open var sequenceIndex: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var sequenceNumber: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var causeMessage: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var aggregateIdentifier: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var causeType: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var deadLetterId: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var eventIdentifier: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var messageType: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var payloadRevision: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var payloadType: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var processingGroup: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var sequenceIdentifier: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var timeStamp: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    open var tokenType: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    open var type: String?
        set(value): Unit = set(17, value)
        get(): String? = get(17) as String?

    open var diagnostics: Long?
        set(value): Unit = set(18, value)
        get(): Long? = get(18) as Long?

    open var metaData: Long?
        set(value): Unit = set(19, value)
        get(): Long? = get(19) as Long?

    open var payload: Long?
        set(value): Unit = set(20, value)
        get(): Long? = get(20) as Long?

    open var token: Long?
        set(value): Unit = set(21, value)
        get(): Long? = get(21) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised DeadLetterEntryRecord
     */
    constructor(enqueuedAt: OffsetDateTime? = null, lastTouched: OffsetDateTime? = null, processingStarted: OffsetDateTime? = null, sequenceIndex: Long? = null, sequenceNumber: Long? = null, causeMessage: String? = null, aggregateIdentifier: String? = null, causeType: String? = null, deadLetterId: String? = null, eventIdentifier: String? = null, messageType: String? = null, payloadRevision: String? = null, payloadType: String? = null, processingGroup: String? = null, sequenceIdentifier: String? = null, timeStamp: String? = null, tokenType: String? = null, type: String? = null, diagnostics: Long? = null, metaData: Long? = null, payload: Long? = null, token: Long? = null): this() {
        this.enqueuedAt = enqueuedAt
        this.lastTouched = lastTouched
        this.processingStarted = processingStarted
        this.sequenceIndex = sequenceIndex
        this.sequenceNumber = sequenceNumber
        this.causeMessage = causeMessage
        this.aggregateIdentifier = aggregateIdentifier
        this.causeType = causeType
        this.deadLetterId = deadLetterId
        this.eventIdentifier = eventIdentifier
        this.messageType = messageType
        this.payloadRevision = payloadRevision
        this.payloadType = payloadType
        this.processingGroup = processingGroup
        this.sequenceIdentifier = sequenceIdentifier
        this.timeStamp = timeStamp
        this.tokenType = tokenType
        this.type = type
        this.diagnostics = diagnostics
        this.metaData = metaData
        this.payload = payload
        this.token = token
        resetTouchedOnNotNull()
    }
}
