/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DomainEventEntryRecord() : UpdatableRecordImpl<DomainEventEntryRecord>(com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY) {

    open var globalIndex: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var sequenceNumber: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var aggregateIdentifier: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var eventIdentifier: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var payloadRevision: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var payloadType: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var timeStamp: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var type: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var metaData: Long?
        set(value): Unit = set(8, value)
        get(): Long? = get(8) as Long?

    open var payload: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised DomainEventEntryRecord
     */
    constructor(globalIndex: Long? = null, sequenceNumber: Long? = null, aggregateIdentifier: String? = null, eventIdentifier: String? = null, payloadRevision: String? = null, payloadType: String? = null, timeStamp: String? = null, type: String? = null, metaData: Long? = null, payload: Long? = null): this() {
        this.globalIndex = globalIndex
        this.sequenceNumber = sequenceNumber
        this.aggregateIdentifier = aggregateIdentifier
        this.eventIdentifier = eventIdentifier
        this.payloadRevision = payloadRevision
        this.payloadType = payloadType
        this.timeStamp = timeStamp
        this.type = type
        this.metaData = metaData
        this.payload = payload
        resetTouchedOnNotNull()
    }
}
