/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.records


import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class EventStoreRecord() : UpdatableRecordImpl<EventStoreRecord>(com.michal.jooq.`public`.tables.EventStore.EVENT_STORE) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var payload: JSONB?
        set(value): Unit = set(1, value)
        get(): JSONB? = get(1) as JSONB?

    open var metadata: JSONB?
        set(value): Unit = set(2, value)
        get(): JSONB? = get(2) as JSONB?

    open var streamId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var version: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised EventStoreRecord
     */
    constructor(id: UUID? = null, payload: JSONB? = null, metadata: JSONB? = null, streamId: String? = null, version: Int? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.payload = payload
        this.metadata = metadata
        this.streamId = streamId
        this.version = version
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
