/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.records


import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class MerchantProjectionRecord() : UpdatableRecordImpl<MerchantProjectionRecord>(com.michal.jooq.`public`.tables.MerchantProjection.MERCHANT_PROJECTION) {

    open var merchantId: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var `data`: JSONB?
        set(value): Unit = set(1, value)
        get(): JSONB? = get(1) as JSONB?

    open var latestSequenceNumber: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised MerchantProjectionRecord
     */
    constructor(merchantId: UUID? = null, `data`: JSONB? = null, latestSequenceNumber: Long? = null): this() {
        this.merchantId = merchantId
        this.`data` = `data`
        this.latestSequenceNumber = latestSequenceNumber
        resetTouchedOnNotNull()
    }
}
