/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class SagaEntryRecord() : UpdatableRecordImpl<SagaEntryRecord>(com.michal.jooq.`public`.tables.SagaEntry.SAGA_ENTRY) {

    open var revision: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var sagaId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var sagaType: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var serializedSaga: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised SagaEntryRecord
     */
    constructor(revision: String? = null, sagaId: String? = null, sagaType: String? = null, serializedSaga: Long? = null): this() {
        this.revision = revision
        this.sagaId = sagaId
        this.sagaType = sagaType
        this.serializedSaga = serializedSaga
        resetTouchedOnNotNull()
    }
}
