/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.records


import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class TokenEntryRecord() : UpdatableRecordImpl<TokenEntryRecord>(com.michal.jooq.`public`.tables.TokenEntry.TOKEN_ENTRY) {

    open var segment: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var owner: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var processorName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var timestamp: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var tokenType: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var token: Long?
        set(value): Unit = set(5, value)
        get(): Long? = get(5) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, String?> = super.key() as Record2<Int?, String?>

    /**
     * Create a detached, initialised TokenEntryRecord
     */
    constructor(segment: Int? = null, owner: String? = null, processorName: String? = null, timestamp: String? = null, tokenType: String? = null, token: Long? = null): this() {
        this.segment = segment
        this.owner = owner
        this.processorName = processorName
        this.timestamp = timestamp
        this.tokenType = tokenType
        this.token = token
        resetTouchedOnNotNull()
    }
}
