/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`


import com.michal.jooq.DefaultCatalog

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.event_store</code>.
     */
    val EVENT_STORE: com.michal.jooq.`public`.tables.EventStore get() = com.michal.jooq.`public`.tables.EventStore.EVENT_STORE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        com.michal.jooq.`public`.tables.EventStore.EVENT_STORE
    )
}
