/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`


import com.michal.jooq.DefaultCatalog

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.association_value_entry</code>.
     */
    val ASSOCIATION_VALUE_ENTRY: com.michal.jooq.`public`.tables.AssociationValueEntry get() = com.michal.jooq.`public`.tables.AssociationValueEntry.ASSOCIATION_VALUE_ENTRY

    /**
     * The table <code>public.dead_letter_entry</code>.
     */
    val DEAD_LETTER_ENTRY: com.michal.jooq.`public`.tables.DeadLetterEntry get() = com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY

    /**
     * The table <code>public.domain_event_entry</code>.
     */
    val DOMAIN_EVENT_ENTRY: com.michal.jooq.`public`.tables.DomainEventEntry get() = com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY

    /**
     * The table <code>public.merchant_projection</code>.
     */
    val MERCHANT_PROJECTION: com.michal.jooq.`public`.tables.MerchantProjection get() = com.michal.jooq.`public`.tables.MerchantProjection.MERCHANT_PROJECTION

    /**
     * The table <code>public.saga_entry</code>.
     */
    val SAGA_ENTRY: com.michal.jooq.`public`.tables.SagaEntry get() = com.michal.jooq.`public`.tables.SagaEntry.SAGA_ENTRY

    /**
     * The table <code>public.snapshot_event_entry</code>.
     */
    val SNAPSHOT_EVENT_ENTRY: com.michal.jooq.`public`.tables.SnapshotEventEntry get() = com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY

    /**
     * The table <code>public.token_entry</code>.
     */
    val TOKEN_ENTRY: com.michal.jooq.`public`.tables.TokenEntry get() = com.michal.jooq.`public`.tables.TokenEntry.TOKEN_ENTRY

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getSequences(): List<Sequence<*>> = listOf(
        com.michal.jooq.`public`.sequences.DOMAIN_EVENT_ENTRY_SEQ
    )

    override fun getTables(): List<Table<*>> = listOf(
        com.michal.jooq.`public`.tables.AssociationValueEntry.ASSOCIATION_VALUE_ENTRY,
        com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY,
        com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY,
        com.michal.jooq.`public`.tables.MerchantProjection.MERCHANT_PROJECTION,
        com.michal.jooq.`public`.tables.SagaEntry.SAGA_ENTRY,
        com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY,
        com.michal.jooq.`public`.tables.TokenEntry.TOKEN_ENTRY
    )
}
