@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.references




/**
 * The table <code>public.event_store</code>.
 */
val EVENT_STORE: com.michal.jooq.`public`.tables.EventStore = com.michal.jooq.`public`.tables.EventStore.EVENT_STORE
