@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.michal.jooq.`public`.tables.references




/**
 * The table <code>public.association_value_entry</code>.
 */
val ASSOCIATION_VALUE_ENTRY: com.michal.jooq.`public`.tables.AssociationValueEntry = com.michal.jooq.`public`.tables.AssociationValueEntry.ASSOCIATION_VALUE_ENTRY

/**
 * The table <code>public.dead_letter_entry</code>.
 */
val DEAD_LETTER_ENTRY: com.michal.jooq.`public`.tables.DeadLetterEntry = com.michal.jooq.`public`.tables.DeadLetterEntry.DEAD_LETTER_ENTRY

/**
 * The table <code>public.domain_event_entry</code>.
 */
val DOMAIN_EVENT_ENTRY: com.michal.jooq.`public`.tables.DomainEventEntry = com.michal.jooq.`public`.tables.DomainEventEntry.DOMAIN_EVENT_ENTRY

/**
 * The table <code>public.merchant_projection</code>.
 */
val MERCHANT_PROJECTION: com.michal.jooq.`public`.tables.MerchantProjection = com.michal.jooq.`public`.tables.MerchantProjection.MERCHANT_PROJECTION

/**
 * The table <code>public.saga_entry</code>.
 */
val SAGA_ENTRY: com.michal.jooq.`public`.tables.SagaEntry = com.michal.jooq.`public`.tables.SagaEntry.SAGA_ENTRY

/**
 * The table <code>public.snapshot_event_entry</code>.
 */
val SNAPSHOT_EVENT_ENTRY: com.michal.jooq.`public`.tables.SnapshotEventEntry = com.michal.jooq.`public`.tables.SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY

/**
 * The table <code>public.token_entry</code>.
 */
val TOKEN_ENTRY: com.michal.jooq.`public`.tables.TokenEntry = com.michal.jooq.`public`.tables.TokenEntry.TOKEN_ENTRY
